include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: false
    prefer_const_constructors: true

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
    prefer_const_constructors: error